import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import SideMenu from "./components/SideMenu";
import SharingStatesContext from "../../useContext/sharedStates";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ფული მაიტათ ჩვენ გასწავლით",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <SharingStatesContext>
          <div className="">
            <Header />
            {children}
            <Footer />
            <SideMenu />
          </div>
          </SharingStatesContext>
      </body>
    </html>
  );
}
